version: v{build}
image:
  - Visual Studio 2017
clone_folder: c:\project\source
skip_tags: false
branches:
  only:
    - master
build_script:
- cmd: >-
    choco install ptime
    
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

    .\build_msvc.bat
after_build:
- cmd: >-
    7z a ptimer.zip %APPVEYOR_BUILD_FOLDER%\build\ptimer.exe
artifacts:
  - path: ptimer.zip
    name: ptimer
deploy:
  tag: $(appveyor_repo_tag_name)
  release: ptimer $(appveyor_repo_tag_name)
  description: 'Release $(appveyor_repo_tag_name)'
  provider: GitHub
  auth_token:
    secure: DYtglKYbFY2kCjJMC8WW0Geeh9WRuZwl2YXZYQUSwgE+ibABWzsxmxD+uEzcFi4Y
  artifact: ptimer.zip
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only