image:
  - Visual Studio 2017
clone_folder: c:\project\source
build_script:
- cmd: >-
    choco install ptime

    .\build_msvc.bat
after_build:
- cmd: >-
    7z a ptimer.zip %APPVEYOR_BUILD_FOLDER%\build\ptimer.exe
artifacts:
  - path: ptimer.zip
    name: ptimer
